# Generated by Django 5.1.3 on 2024-11-29 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_user_rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 0), django.core.validators.MaxValueValidator(10, 0)], verbose_name='Average User Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Movie Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Release Year'),
        ),
    ]
